# Generated by Django 3.2.12 on 2022-03-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('storage_count', models.PositiveSmallIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('product_img', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
