# Generated by Django 3.2.12 on 2022-03-31 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
